version: "3"

services:
  blazor-ui:
    container_name: blazor-ui
    build:
      context: BlazorWorkshopApp
      dockerfile: Dockerfile
    image: blazor-ui
    ports:
      - "5056:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
    networks: ['workshop']
  workshop-api:
    container_name: workshop-api
    build:
      context: WorkshopAPI
      dockerfile: Dockerfile
    image: workshop-api
    ports:
      - "5059:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
    networks: ['workshop']
  workshop-db:
    container_name: workshop-db
    build:
      context: ./
      dockerfile: DockerfileSQLDB
    image: "workshop-db"
    environment:
      SA_PASSWORD: "YourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5040:1433"
    networks: ['workshop']
networks:
  workshop:
