USE [master]
GO

CREATE DATABASE [Workshop]
 CONTAINMENT = NONE

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Workshop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Workshop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Workshop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Workshop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Workshop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Workshop] SET ARITHABORT OFF 
GO

ALTER DATABASE [Workshop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Workshop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Workshop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Workshop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Workshop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Workshop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Workshop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Workshop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Workshop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Workshop] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Workshop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Workshop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Workshop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Workshop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Workshop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Workshop] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Workshop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Workshop] SET RECOVERY FULL 
GO

ALTER DATABASE [Workshop] SET  MULTI_USER 
GO

ALTER DATABASE [Workshop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Workshop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Workshop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Workshop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Workshop] SET DELAYED_DURABILITY = DISABLED 
GO

-- ALTER DATABASE [Workshop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
-- GO

ALTER DATABASE [Workshop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Workshop] SET  READ_WRITE 
GO